//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabinet_Medicale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medecin
    {
        public Medecin()
        {
            this.RDVs = new HashSet<RDV>();
        }
    
        public string CodeMedecin { get; set; }
        public string NomMedecin { get; set; }
        public string TelMedecin { get; set; }
        public Nullable<System.DateTime> DateEmbauche { get; set; }
        public string SpecialiteMedecin { get; set; }
    
        public virtual Specialite Specialite { get; set; }
        public virtual ICollection<RDV> RDVs { get; set; }
    }
}
