//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabinet_Medicale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.RDVs = new HashSet<RDV>();
        }
    
        public string CodePatient { get; set; }
        public string NomPatient { get; set; }
        public string AdressePatient { get; set; }
        public Nullable<System.DateTime> DateNaissance { get; set; }
        public string SexePatient { get; set; }
    
        public virtual ICollection<RDV> RDVs { get; set; }
    }
}
