//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabinet_Medicale
{
    using System;
    using System.Collections.Generic;
    
    public partial class RDV
    {
        public int NumeroRDV { get; set; }
        public Nullable<System.DateTime> DateRDV { get; set; }
        public string HeureRDV { get; set; }
        public string CodeMedecin { get; set; }
        public string CodePatient { get; set; }
    
        public virtual Medecin Medecin { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
