//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabinet_Medicale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialite
    {
        public Specialite()
        {
            this.Medecins = new HashSet<Medecin>();
        }
    
        public string Code { get; set; }
        public string Nom { get; set; }
    
        public virtual ICollection<Medecin> Medecins { get; set; }
    }
}
